stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1  # Change to your AWS region
  AMPLIFY_APP_ID: ${AMPLIFY_APP_ID}  # Will be set in GitLab CI/CD variables
  AMPLIFY_BRANCH: ${AMPLIFY_BRANCH}  # Will be set in GitLab CI/CD variables

# Cache dependencies between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Install AWS CLI in all jobs that need it
.aws-cli-template: &aws-cli-template
  before_script:
    - apt-get update -y
    - apt-get install -y python3-pip curl unzip
    - pip3 install awscli
    - aws --version
    - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
    - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
    - aws configure set region ${AWS_DEFAULT_REGION}

# Build the application
build:
  stage: build
  image: node:18-alpine
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 week
  only:
    - main
    - develop
  tags:
    - docker-ci

# Deploy to AWS Amplify
deploy:
  stage: deploy
  image: python:3.9
  <<: *aws-cli-template
  script:
    - echo "Creating deployment for app ID ${AMPLIFY_APP_ID} on branch ${AMPLIFY_BRANCH}"
    - DEPLOYMENT_ID=$(aws amplify create-deployment --app-id ${AMPLIFY_APP_ID} --branch-name ${AMPLIFY_BRANCH} --output json | jq -r '.jobId')
    - echo "Starting deployment with ID ${DEPLOYMENT_ID}"
    - aws amplify start-deployment --app-id ${AMPLIFY_APP_ID} --branch-name ${AMPLIFY_BRANCH} --job-id ${DEPLOYMENT_ID}
    - echo "Deployment started. Check the AWS Amplify Console for status."
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: https://${AMPLIFY_BRANCH}.${AMPLIFY_APP_ID}.amplifyapp.com
  only:
    - main
    - develop
  tags:
    - docker-ci

